# Netlify configuration for frontend-only deployment
[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

# Environment variables for frontend
[build.environment]
  REACT_APP_API_URL = "https://your-backend-api.com"
  GENERATE_SOURCEMAP = "false"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (if using Netlify Functions)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.com/api/:splat"
  status = 200
  force = true