services:
  # Backend API Service
  - type: web
    name: user-management-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend Static Site
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build