services:
  # Backend API Service
  - type: web
    name: user-management-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://user-management-frontend.onrender.com

  # Frontend Static Site
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: cd frontend && npm install && REACT_APP_API_URL=https://user-management-api.onrender.com npm run build
    staticPublishPath: ./frontend/build